# Problem Statement

Masyarakat awam kesulitan menentukan harga jual Vespa klasik karena harganya melambung tinggi dan tidak memiliki standar pasaran yang pasti seperti motor biasa. Menggabungkan perhitungan HPP (harga beli ditambah biaya restorasi) dan survei harga pasar. Harga yang tinggi tersebut dapat diterima oleh pembeli karena tingginya tingkat kelangkaan, nilai historis, serta status Vespa klasik.

https://ejournal.undiksha.ac.id/index.php/JJA/article/view/36830

# Import Data

In [2]:
import pandas as pd
import numpy as np
from scipy.stats import zscore
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
## Import Excel
df = pd.read_csv("Auto Sales data.csv")

df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,DAYS_SINCE_LASTORDER,STATUS,PRODUCTLINE,MSRP,PRODUCTCODE,CUSTOMERNAME,PHONE,ADDRESSLINE1,CITY,POSTALCODE,COUNTRY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,24/02/2018,828,Shipped,Motorcycles,95,S10_1678,Land of Toys Inc.,2125557818,897 Long Airport Avenue,NYC,10022,USA,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,07/05/2018,757,Shipped,Motorcycles,95,S10_1678,Reims Collectables,26.47.1555,59 rue de l'Abbaye,Reims,51100,France,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,01/07/2018,703,Shipped,Motorcycles,95,S10_1678,Lyon Souveniers,+33 1 46 62 7555,27 rue du Colonel Pierre Avia,Paris,75508,France,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,25/08/2018,649,Shipped,Motorcycles,95,S10_1678,Toys4GrownUps.com,6265557265,78934 Hillside Dr.,Pasadena,90003,USA,Young,Julie,Medium
4,10168,36,96.66,1,3479.76,28/10/2018,586,Shipped,Motorcycles,95,S10_1678,Technics Stores Inc.,6505556809,9408 Furth Circle,Burlingame,94217,USA,Hirano,Juri,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2742,10350,20,112.22,15,2244.40,02/12/2019,2924,Shipped,Ships,54,S72_3212,Euro Shopping Channel,(91) 555 94 44,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Small
2743,10373,29,137.19,1,3978.51,31/01/2020,2865,Shipped,Ships,54,S72_3212,"Oulu Toy Supplies, Inc.",981-443655,Torikatu 38,Oulu,90110,Finland,Koskitalo,Pirkko,Medium
2744,10386,43,125.99,4,5417.57,01/03/2020,2836,Resolved,Ships,54,S72_3212,Euro Shopping Channel,(91) 555 94 44,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Medium
2745,10397,34,62.24,1,2116.16,28/03/2020,2810,Shipped,Ships,54,S72_3212,Alpha Cognac,61.77.6555,1 rue Alsace-Lorraine,Toulouse,31000,France,Roulet,Annette,Small
2746,10414,47,65.52,9,3079.44,06/05/2020,2772,On Hold,Ships,54,S72_3212,Gifts4AllAges.com,6175559555,8616 Spinnaker Dr.,Boston,51003,USA,Yoshido,Juri,Medium

## head()

In [3]:
'''
Kode head() ini digunakan untuk Menampilkan 5 baris pertama (default) dan untuk menampilkan Nama kolom apa saja yang ada
'''
# Copy data biar tidak ditiban
df_copy = df.copy()
df_copy.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,DAYS_SINCE_LASTORDER,STATUS,PRODUCTLINE,MSRP,PRODUCTCODE,CUSTOMERNAME,PHONE,ADDRESSLINE1,CITY,POSTALCODE,COUNTRY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,24/02/2018,828,Shipped,Motorcycles,95,S10_1678,Land of Toys Inc.,2125557818,897 Long Airport Avenue,NYC,10022,USA,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,07/05/2018,757,Shipped,Motorcycles,95,S10_1678,Reims Collectables,26.47.1555,59 rue de l'Abbaye,Reims,51100,France,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,01/07/2018,703,Shipped,Motorcycles,95,S10_1678,Lyon Souveniers,+33 1 46 62 7555,27 rue du Colonel Pierre Avia,Paris,75508,France,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,25/08/2018,649,Shipped,Motorcycles,95,S10_1678,Toys4GrownUps.com,6265557265,78934 Hillside Dr.,Pasadena,90003,USA,Young,Julie,Medium
4,10168,36,96.66,1,3479.76,28/10/2018,586,Shipped,Motorcycles,95,S10_1678,Technics Stores Inc.,6505556809,9408 Furth Circle,Burlingame,94217,USA,Hirano,Juri,Medium

## Info

In [4]:
'''
Kode infp() ini digunakan untuk Menampilkan, Jumlah baris dan kolom, tipe data, dan jumlah missing value
'''
# Info data
df_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 2747 entries, 0 to 2746
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ORDERNUMBER           2747 non-null   int64
 1   QUANTITYORDERED       2747 non-null   int64
 2   PRICEEACH             2747 non-null   float64
 3   ORDERLINENUMBER       2747 non-null   int64
 4   SALES                 2747 non-null   float64
 5   ORDERDATE             2747 non-null   str
 6   DAYS_SINCE_LASTORDER  2747 non-null   int64
 7   STATUS                2747 non-null   str
 8   PRODUCTLINE           2747 non-null   str
 9   MSRP                  2747 non-null   int64
 10  PRODUCTCODE           2747 non-null   str
 11  CUSTOMERNAME          2747 non-null   str
 12  PHONE                 2747 non-null   str
 13  ADDRESSLINE1          2747 non-null   str
 14  CITY                  2747 non-null   str
 15  POSTALCODE            2747 non-null   str
 16  COUNTRY               2747 non-null   str
 17  CONTACTLASTNAME       2747 non-null   str
 18  CONTACTFIRSTNAME      2747 non-null   str
 19  DEALSIZE              2747 non-null   str
dtypes: float64(2), int64(5), str(13)
memory usage: 761.5 KB

Data Auto Sales merupakan data penjualan barang yang memiliki 2747 Baris dan 20 Kolom, data superstore ini memiliki 13 string, 5 int dan 2 float. tetapi ada beberapa data kolom yang perluh diubah tipe datanya seperti ORDERDATE menjadi tipe DATE

In [5]:
Missing = df_copy.isnull().sum()
print(f"Missing Value:")
print(Missing)

Missing Value:
ORDERNUMBER             0
QUANTITYORDERED         0
PRICEEACH               0
ORDERLINENUMBER         0
SALES                   0
ORDERDATE               0
DAYS_SINCE_LASTORDER    0
STATUS                  0
PRODUCTLINE             0
MSRP                    0
PRODUCTCODE             0
CUSTOMERNAME            0
PHONE                   0
ADDRESSLINE1            0
CITY                    0
POSTALCODE              0
COUNTRY                 0
CONTACTLASTNAME         0
CONTACTFIRSTNAME        0
DEALSIZE                0
dtype: int64

## Duplikasi

In [6]:
'''
Saya menggunakan kode duplicated untuk mencari data yang terdapat duplikate (data yang sama), setelah meancari saya mengubah jumlah
data menjadi persen.
'''
## Duplicated 
SemuaData = df_copy.duplicated().sum()

#Buat jadi %
a = SemuaData / len(df_copy) * 100
print("=" * 50)
print(f"Duplikat: {SemuaData}")
print(f"Duplikat persen: {a:.2f}%")
print("=" * 50)

==================================================
Duplikat: 0
Duplikat persen: 0.00%
==================================================

## Konsistensi

### ORDERDATE

In [7]:
TypoORDERDATE = df_copy["ORDERDATE"].unique()
print(f"Typo ORDERDATE: {TypoORDERDATE}")
print("=" * 50)

Typo ORDERDATE: <ArrowStringArray>
['24/02/2018', '07/05/2018', '01/07/2018', '25/08/2018', '28/10/2018',
 '11/11/2018', '18/11/2018', '15/01/2019', '20/02/2019', '05/04/2019',
 ...
 '29/03/2019', '28/02/2020', '20/04/2019', '02/03/2020', '11/04/2018',
 '13/08/2018', '08/10/2018', '01/12/2018', '28/03/2020', '21/04/2018']
Length: 246, dtype: str
==================================================

### STATUS

In [9]:
TypoSTATUS = df_copy["STATUS"].unique()
print(f"Typo STATUS: {TypoSTATUS}")
print("=" * 50)

Typo STATUS: <ArrowStringArray>
['Shipped', 'Disputed', 'In Process', 'Cancelled', 'On Hold', 'Resolved']
Length: 6, dtype: str
==================================================

### PRODUCTLINE

In [10]:
TypoPRODUCTLINE = df_copy["PRODUCTLINE"].unique()
print(f"Typo PRODUCTLINE: {TypoPRODUCTLINE}")
print("=" * 50)

Typo PRODUCTLINE: <ArrowStringArray>
[     'Motorcycles',     'Classic Cars', 'Trucks and Buses',
     'Vintage Cars',           'Planes',            'Ships',
           'Trains']
Length: 7, dtype: str
==================================================

### PRODUCTCODE

In [11]:
TypoPRODUCTCODE = df_copy["PRODUCTCODE"].unique()
print(f"Typo PRODUCTCODE: {TypoPRODUCTCODE}")
print("=" * 50)

Typo PRODUCTCODE: <ArrowStringArray>
[ 'S10_1678',  'S10_1949',  'S10_2016',  'S10_4698',  'S10_4757',  'S10_4962',
  'S12_1099',  'S12_1108',  'S12_1666',  'S12_2823',
 ...
 'S700_2466', 'S700_2610', 'S700_2824', 'S700_2834', 'S700_3167', 'S700_3505',
 'S700_3962', 'S700_4002',  'S72_1253',  'S72_3212']
Length: 109, dtype: str
==================================================

### CUSTOMERNAME

In [12]:
TypoCUSTOMERNAME = df_copy["CUSTOMERNAME"].unique()
print(f"Typo CUSTOMERNAME: {TypoCUSTOMERNAME}")
print("=" * 50)

Typo CUSTOMERNAME: <ArrowStringArray>
[                 'Land of Toys Inc.',                 'Reims Collectables',
                    'Lyon Souveniers',                  'Toys4GrownUps.com',
               'Technics Stores Inc.',           'Daedalus Designs Imports',
                       'Herkku Gifts',                   'Auto Canal Petit',
         'Australian Collectors, Co.',                    'Vitachrome Inc.',
            'Tekni Collectables Inc.',                    'Gift Depot Inc.',
                  'La Rochelle Gifts',               'Marta's Replicas Co.',
               'Toys of Finland, Co.',                 'Baane Mini Imports',
              'Diecast Classics Inc.',              'Salzburg Collectables',
          'Souveniers And Things Co.',                   'FunGiftIdeas.com',
              'UK Collectables, Ltd.',              'Euro Shopping Channel',
           'Volvo Model Replicas, Co',         'Corrida Auto Replicas, Ltd',
            'Dragon Souveniers, Ltd.',               'Classic Legends Inc.',
        'Australian Gift Network, Co',            'Classic Gift Ideas, Inc',
             'Saveley & Henriot, Co.',     'Canadian Gift Exchange Network',
        'West Coast Collectables Co.',         'Cambridge Collectables Co.',
                   'Super Scale Inc.',            'Tokyo Collectables, Ltd',
                 'Amica Models & Co.',            'Scandinavian Gift Ideas',
                 'Auto Assoc. & Cie.',       'Mini Gifts Distributors Ltd.',
       'Online Diecast Creations Co.',         'Collectables For Less Inc.',
            'Anna's Decorations, Ltd',       'Quebec Home Shopping Network',
               'Osaka Souveniers Co.',       'Motor Mint Distributors Inc.',
                  'Atelier graphique',                      'Mini Classics',
           'Danish Wholesale Imports',           'Stylish Desk Decors, Co.',
                'Mini Creations Ltd.',                       'Alpha Cognac',
     'Double Decker Gift Stores, Ltd',                 'Enaco Distributors',
       'Collectable Mini Designs Co.',                         'Petit Auto',
  'Royal Canadian Collectables, Ltd.',                  'Gifts4AllAges.com',
                  'giftsbymail.co.uk',            'Oulu Toy Supplies, Inc.',
          'The Sharp Gifts Warehouse',          'La Corne D'abondance, Co.',
                    'Mini Auto Werke',               'Diecast Collectables',
                   'Handji Gifts& Co',                    'Cruz & Sons Co.',
               'Marseille Mini Autos',             'Toms Spezialitten, Ltd',
                    'Vida Sport, Ltd',                'L'ordine Souveniers',
           'Online Mini Collectables',               'Blauer See Auto, Co.',
                'Suominen Souveniers',                 'Muscle Machine Inc',
            'Clover Collections, Co.',                        'CAF Imports',
                     'AV Stores, Co.',               'Heintze Collectables',
                    'Microscale Inc.',                  'Boards & Toys Co.',
         'Iberia Gift Imports, Corp.',           'Signal Collectibles Ltd.',
                        'Mini Caravy',                 'Signal Gift Stores',
          'Norway Gifts By Mail, Co.',                      'Rovelli Gifts',
       'Australian Collectables, Ltd',                   'Gift Ideas Corp.',
 'Bavarian Collectables Imports, Co.',                       'Royale Belge',
            'Auto-Moto Classics Inc.']
Length: 89, dtype: str
==================================================

### PHONE

In [13]:
TypoPHONE = df_copy["PHONE"].unique()
print(f"Typo PHONE: {TypoPHONE}")
print("=" * 50)

Typo PHONE: <ArrowStringArray>
[       '2125557818',        '26.47.1555',  '+33 1 46 62 7555',
        '6265557265',        '6505556809',        '20.16.1555',
     '+47 2267 3215',    '(1) 47.55.6555',      '03 9520 4555',
        '2125551500',        '2015559350',        '2035552570',
        '40.67.8555',        '6175558555',       '90-224 8555',
        '07-98 9555',        '2155551555',         '6562-9555',
   '+61 2 9495 8555',        '5085552555',    '(171) 555-2282',
    '(91) 555 94 44',      '0921-12 3555',    '(91) 555 22 82',
      '+65 221 7555',        '2125558493',    '61-7-3844-6555',
        '2155554695',        '78.32.5555',    '(604) 555-3392',
        '3105553722',        '6175555555',        '2035559545',
   '+81 3 3584 0555',       '011-4988555',      '0695-34 6555',
        '30.59.8555',        '4155551450',        '6035558647',
      '02 9936 8555',    '(514) 555-8054',  '+81 06 6342 5555',
        '2155559857',        '40.32.2555',        '9145554562',
        '31 12 3555',    '(171) 555-0297',        '5085559555',
        '61.77.6555',    '(171) 555-7555',     '(93) 203 4555',
        '7605558146',      '(02) 5554 67',    '(604) 555-4555',
        '6175559555',    '(198) 555-8888',        '981-443655',
        '4085553659',    '(1) 42.34.2555',         '7675-3555',
        '6175552555',      '+65 224 1555',    '+63 2 555 3587',
        '91.24.4555',      '0221-5554327',       '0897-034555',
       '0522-556555',        '6175557555', '+49 69 66 90 2555',
   '+358 9 8045 555',        '2125557413',    '+353 1862 1555',
   '+34 913 728 555',    '(171) 555-1555',        '86 21 3555',
        '2125551957',        '3105552373',    '(95) 555 82 82',
        '4155554312',        '88.60.1555',        '7025551838',
     '+47 2212 1555',        '035-640555',    '61-9-3844-6555',
        '2035554407', '+49 89 61 08 9555',  '(071) 23 67 2555',
        '6175558428']
Length: 88, dtype: str
==================================================

### ADDRESSLINE1

In [14]:
TypoADDRESSLINE1 = df_copy["ADDRESSLINE1"].unique()
print(f"Typo ADDRESSLINE1: {TypoADDRESSLINE1}")
print("=" * 50)

Typo ADDRESSLINE1: <ArrowStringArray>
[                   '897 Long Airport Avenue',
                         '59 rue de l'Abbaye',
              '27 rue du Colonel Pierre Avia',
                         '78934 Hillside Dr.',
                          '9408 Furth Circle',
                    '184, chausse de Tournai',
                'Drammen 121, PR 744 Sentrum',
                          '25, rue Lauriston',
                          '636 St Kilda Road',
                          '2678 Kingston Rd.',
                              '7476 Moss Rd.',
                        '25593 South Bay Ln.',
               '67, rue des Cinquante Otages',
                        '39323 Spinnaker Dr.',
                              'Keskuskatu 45',
                     'Erling Skakkes gate 78',
                           '7586 Pompton St.',
                                'Geislweg 14',
    'Monitor Money Building, 815 Pacific Hwy',
                          '1785 First Street',
               'Berkeley Gardens 12  Brewery',
                         'C/ Moralzarzal, 86',
                            'Berguvsvgen  8',
                             'C/ Araquil, 67',
       'Bronz Sok., Bronz Apt. 3/6 Tesvikiye',
                           '5905 Pompton St.',
                     '31 Duncan St. West End',
                           '782 First Street',
                         '2, rue du Commerce',
                               '1900 Oak St.',
                          '3675 Furth Circle',
                             '4658 Baden Av.',
                   '567 North Pendale Street',
                             '2-2-8 Roppongi',
                        'Via Monte Bianco 34',
                               '?kergatan 24',
                     '67, avenue de l'Europe',
                            '5677 Strong St.',
                   '2304 Long Airport Avenue',
                           '7825 Douglas Av.',
                          '201 Miller Street',
                         '43 rue St. Laurent',
   'Dojima Avanza 4F, 1-6-20 Dojima, Kita-ku',
                          '11328 Douglas Av.',
                             '54, rue Royale',
                  '3758 North Pendale Street',
                               'Vinb'ltet 34',
                             '35 King George',
                          '4575 Hillside Dr.',
                      '1 rue Alsace-Lorraine',
                            '120 Hanover Sq.',
                     'Rambla de Catalu¤a, 23',
                           '361 Furth Circle',
                        'Rue Joseph-Bens 532',
                         '23 Tsawassen Blvd.',
                         '8616 Spinnaker Dr.',
                  'Garden House Crowther Way',
                                'Torikatu 38',
                             '3086 Ingle Ln.',
                    '265, boulevard Charonne',
                               'Kirchgasse 6',
                             '6251 Ingle Ln.',
    'Village Close - 106 Linden Road Sandown',
 '15 McCallum Street - NatWest Center #13-03',
                       '12, rue des Bouchers',
                         'Mehrheimerstr. 369',
                          'Grenzacherweg 237',
                     'Strada Provinciale 124',
                         '7635 Spinnaker Dr.',
                              'Lyonerstr. 34',
        'Software Engineering Center, SEC Oy',
                          '4092 Furth Circle',
                             '25 Maiden Lane',
     'Merchants House, 27-30 Merchant's Quay',
                          'Fauntleroy Circus',
                              'Smagsloget 45',
                  '5290 North Pendale Street',
                           '4097 Douglas Av.',
                              'C/ Romero, 33',
                          '2793 Furth Circle',
                           '24, place Kluber',
                            '8489 Strong St.',
        'Drammensveien 126 A, PB 744 Sentrum',
                    'Via Ludovico il Moro 22',
                             '7 Allen Street',
                           '2440 Pompton St.',
                               'Hansastr. 15',
                       'Boulevard Tirou, 255',
                          '16780 Pompton St.']
Length: 89, dtype: str
==================================================

#### Insigt

Mencari missing value, duplikasi, dan data yang typo pada data Marketing bisa menggunakan Pyton dan hasilnya: 
- tidak terdapat missing value
- tidak terdapat duplikasi
- tidak ada data yang typo

yang membuat datanya siap untuk pemeriksaan selanjutnya.

In [ ]:


# Inisialisasi LabelEncoder
le = LabelEncoder()

# Daftar kolom yang ingin di-encode
kolom_kategorikal = [
    "ORDERDATE", "STATUS", "PRODUCTLINE", "PRODUCTCODE", "CUSTOMERNAME", 
    "PHONE", "ADDRESSLINE1", "CITY", "POSTALCODE", 
    "COUNTRY", "CONTACTLASTNAME", "CONTACTFIRSTNAME", "DEALSIZE"
]

# Melakukan encoding untuk setiap kolom dan menyimpannya dengan tambahan suffix _C
for col in kolom_kategorikal:
    df_copy[f"{col}_C"] = le.fit_transform(df_copy[col].astype(str))

# Menampilkan beberapa kolom hasil encoding teratas
df_copy[[col + "_C" for col in kolom_kategorikal]].head()

In [ ]:
df_copy

## Outlier

In [ ]:
df_box = df_copy.copy()

# Buat boxplot user_id
plt.figure(figsize=(10, 2)) 
sns.boxplot(x=df_box["ORDERNUMBER"])
plt.title("Boxplot ORDERNUMBER", fontsize=14, fontweight="bold")
plt.ylabel("Jumlah", fontsize=12)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()
print("=" * 100)

In [ ]:
plt.figure(figsize=(10, 2)) 
sns.boxplot(x=df_box["QUANTITYORDERED"])
plt.title("Boxplot QUANTITYORDERED", fontsize=14, fontweight="bold")
plt.ylabel("Jumlah", fontsize=12)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()
print("=" * 100)

In [ ]:
plt.figure(figsize=(10, 2)) 
sns.boxplot(x=df_box["PRICEEACH"])
plt.title("Boxplot PRICEEACH", fontsize=14, fontweight="bold")
plt.ylabel("Jumlah", fontsize=12)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()
print("=" * 100)

In [ ]:
plt.figure(figsize=(10, 2)) 
sns.boxplot(x=df_box["ORDERLINENUMBER"])
plt.title("Boxplot ORDERLINENUMBER", fontsize=14, fontweight="bold")
plt.ylabel("Jumlah", fontsize=12)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()
print("=" * 100)

In [ ]:
plt.figure(figsize=(10, 2)) 
sns.boxplot(x=df_box["SALES"])
plt.title("Boxplot SALES", fontsize=14, fontweight="bold")
plt.ylabel("Jumlah", fontsize=12)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()
print("=" * 100)

In [ ]:
plt.figure(figsize=(10, 2)) 
sns.boxplot(x=df_box["ORDERDATE_C"])
plt.title("Boxplot ORDERDAT_C", fontsize=14, fontweight="bold")
plt.ylabel("Jumlah", fontsize=12)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()
print("=" * 100)

In [ ]:

plt.figure(figsize=(10, 2)) 
sns.boxplot(x=df_box["DAYS_SINCE_LASTORDER"])
plt.title("Boxplot DAYS_SINCE_LASTORDER", fontsize=14, fontweight="bold")
plt.ylabel("Jumlah", fontsize=12)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()
print("=" * 100)

In [ ]:

plt.figure(figsize=(10, 2)) 
sns.boxplot(x=df_box["STATUS_C"])
plt.title("Boxplot STATUS_C", fontsize=14, fontweight="bold")
plt.ylabel("Jumlah", fontsize=12)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()
print("=" * 100)

In [ ]:
plt.figure(figsize=(10, 2)) 
sns.boxplot(x=df_box["PRODUCTLINE_C"])
plt.title("Boxplot PRODUCTLINE_C", fontsize=14, fontweight="bold")
plt.ylabel("Jumlah", fontsize=12)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()
print("=" * 100)

In [ ]:
plt.figure(figsize=(10, 2)) 
sns.boxplot(x=df_box["MSRP"])
plt.title("Boxplot MSRP", fontsize=14, fontweight="bold")
plt.ylabel("Jumlah", fontsize=12)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()
print("=" * 100)

In [ ]:
plt.figure(figsize=(10, 2)) 
sns.boxplot(x=df_box["PRODUCTCODE_C"])
plt.title("Boxplot PRODUCTCODE_C", fontsize=14, fontweight="bold")
plt.ylabel("Jumlah", fontsize=12)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()
print("=" * 100)

In [ ]:

plt.figure(figsize=(10, 2)) 
sns.boxplot(x=df_box["CUSTOMERNAME_C"])
plt.title("Boxplot CUSTOMERNAME_C", fontsize=14, fontweight="bold")
plt.ylabel("Jumlah", fontsize=12)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()
print("=" * 100)

In [ ]:
plt.figure(figsize=(10, 2)) 
sns.boxplot(x=df_box["PHONE_C"])
plt.title("Boxplot PHONE_C", fontsize=14, fontweight="bold")
plt.ylabel("Jumlah", fontsize=12)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()
print("=" * 100)

In [ ]:
plt.figure(figsize=(10, 2)) 
sns.boxplot(x=df_box["ADDRESSLINE1_C"])
plt.title("Boxplot ADDRESSLINE1_C", fontsize=14, fontweight="bold")
plt.ylabel("Jumlah", fontsize=12)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()
print("=" * 100)

In [ ]:
plt.figure(figsize=(10, 2)) 
sns.boxplot(x=df_box["CITY_C"])
plt.title("Boxplot CITY_C", fontsize=14, fontweight="bold")
plt.ylabel("Jumlah", fontsize=12)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()
print("=" * 100)

In [ ]:
plt.figure(figsize=(10, 2)) 
sns.boxplot(x=df_box["POSTALCODE_C"])
plt.title("Boxplot POSTALCODE_C", fontsize=14, fontweight="bold")
plt.ylabel("Jumlah", fontsize=12)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()
print("=" * 100)

In [ ]:
plt.figure(figsize=(10, 2)) 
sns.boxplot(x=df_box["COUNTRY_C"])
plt.title("Boxplot COUNTRY_C", fontsize=14, fontweight="bold")
plt.ylabel("Jumlah", fontsize=12)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()
print("=" * 100)

In [ ]:
plt.figure(figsize=(10, 2)) 
sns.boxplot(x=df_box["CONTACTLASTNAME_C"])
plt.title("Boxplot CONTACTLASTNAME_C", fontsize=14, fontweight="bold")
plt.ylabel("Jumlah", fontsize=12)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()
print("=" * 100)

In [ ]:
plt.figure(figsize=(10, 2)) 
sns.boxplot(x=df_box["CONTACTFIRSTNAME_C"])
plt.title("Boxplot CONTACTFIRSTNAME_C", fontsize=14, fontweight="bold")
plt.ylabel("Jumlah", fontsize=12)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()
print("=" * 100)

In [ ]:
plt.figure(figsize=(10, 2)) 
sns.boxplot(x=df_box["DEALSIZE_C"])
plt.title("Boxplot DEALSIZE_C", fontsize=14, fontweight="bold")
plt.ylabel("Jumlah", fontsize=12)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()
print("=" * 100)

## Outlier Zscore

### QUANTITYORDERED

In [ ]:
dfZ = df_copy
dfZ["z_QUANTITYORDERED"] = zscore(dfZ["QUANTITYORDERED"])
#Mencari Outlier dengan menghitung nilai absolut yang lebih besar dari 2
Outlier_QUANTITYORDERED = dfZ[dfZ["z_QUANTITYORDERED"].abs()>2]
Outlier_QUANTITYORDERED

In [ ]:
ZQUANTITYORDERED = (dfZ["z_QUANTITYORDERED"].abs()>2).sum()
#Buat jadi %
a = ZQUANTITYORDERED / len(df_copy) * 100
print(f"Outlier QUANTITYORDERED: {ZQUANTITYORDERED}")
print(f"Outlier QUANTITYORDERED persen: {a:.2f}%")
#Menghitung Outlier per Category
print("=" * 50)
Outlier_QUANTITYORDERED_per_PRODUCTLINE = dfZ[dfZ["z_QUANTITYORDERED"].abs() > 2].groupby("PRODUCTLINE")["z_QUANTITYORDERED"].count()
print("Jumlah Outlier QUANTITYORDERED per PRODUCTLINE:")
print(Outlier_QUANTITYORDERED_per_PRODUCTLINE)
print("=" * 50)

### PRICEEACH

In [ ]:
dfZ["z_PRICEEACH"] = zscore(dfZ["PRICEEACH"])
#Mencari Outlier dengan menghitung nilai absolut yang lebih besar dari 2
Outlier_PRICEEACH = dfZ[dfZ["z_PRICEEACH"].abs()>2]
Outlier_PRICEEACH

In [ ]:
ZPRICEEACH = (dfZ["z_PRICEEACH"].abs()>2).sum()
#Buat jadi %
a = ZPRICEEACH / len(df_copy) * 100
print(f"Outlier PRICEEACH: {ZPRICEEACH}")
print(f"Outlier PRICEEACH persen: {a:.2f}%")
#Menghitung Outlier per Category
print("=" * 50)
Outlier_PRICEEACH_per_PRODUCTLINE = dfZ[dfZ["z_PRICEEACH"].abs() > 2].groupby("PRODUCTLINE")["z_PRICEEACH"].count()
print("Jumlah Outlier PRICEEACH per PRODUCTLINE:")
print(Outlier_PRICEEACH_per_PRODUCTLINE)
print("=" * 50)

### SALES

In [ ]:
dfZ["z_SALES"] = zscore(dfZ["SALES"])
#Mencari Outlier dengan menghitung nilai absolut yang lebih besar dari 2
Outlier_SALES = dfZ[dfZ["z_SALES"].abs()>2]
Outlier_SALES

In [ ]:
ZSALES = (dfZ["z_SALES"].abs()>2).sum()
#Buat jadi %
a = ZSALES / len(df_copy) * 100
print(f"Outlier SALES: {ZSALES}")
print(f"Outlier SALES persen: {a:.2f}%")
#Menghitung Outlier per Category
print("=" * 50)
Outlier_SALES_per_PRODUCTLINE = dfZ[dfZ["z_SALES"].abs() > 2].groupby("PRODUCTLINE")["z_SALES"].count()
print("Jumlah Outlier SALES per PRODUCTLINE:")
print(Outlier_SALES_per_PRODUCTLINE)
print("=" * 50)

### STATUS

In [ ]:
dfZ["z_STATUS_C"] = zscore(dfZ["STATUS_C"])
#Mencari Outlier dengan menghitung nilai absolut yang lebih besar dari 2
Outlier_STATUS_C = dfZ[dfZ["z_STATUS_C"].abs()>2]
Outlier_STATUS_C

In [ ]:
ZSTATUS_C = (dfZ["z_STATUS_C"].abs()>2).sum()
#Buat jadi %
a = ZSTATUS_C / len(df_copy) * 100
print(f"Outlier STATUS_C: {ZSTATUS_C}")
print(f"Outlier STATUS_C persen: {a:.2f}%")
#Menghitung Outlier per Category
print("=" * 50)
Outlier_STATUS_C_per_PRODUCTLINE = dfZ[dfZ["z_STATUS_C"].abs() > 2].groupby("PRODUCTLINE")["z_STATUS_C"].count()
print("Jumlah Outlier STATUS_C per PRODUCTLINE:")
print(Outlier_STATUS_C_per_PRODUCTLINE)
print("=" * 50)

## EDA

### Unvariate

In [ ]:
kolom_pilihan = [
    "ORDERNUMBER", 
    "QUANTITYORDERED", 
    "PRICEEACH", 
    "ORDERLINENUMBER", 
    "SALES", 
    "DAYS_SINCE_LASTORDER", 
    "MSRP"
]

plt.figure(figsize=(12, 8))
df_copy[kolom_pilihan].hist(bins=20, figsize=(20, 10), color="orange")
plt.title("Distribusi Variable Numerik")
plt.show()

In [ ]:
kolom_kategorikal = [
    "ORDERDATE_C", "STATUS_C", "PRODUCTLINE_C", "PRODUCTCODE_C", "CUSTOMERNAME_C", 
    "PHONE_C", "ADDRESSLINE1_C", "CITY_C", "POSTALCODE_C", 
    "COUNTRY_C", "CONTACTLASTNAME_C", "CONTACTFIRSTNAME_C", "DEALSIZE_C"
]

plt.figure(figsize=(12, 8))
df_copy[kolom_kategorikal].hist(bins=20, figsize=(20, 10), color="orange")
plt.title("Distribusi Variable Numerik")
plt.show()

### Heatmap

In [ ]:
corr = df_copy[["ORDERNUMBER", 
    "QUANTITYORDERED", 
    "PRICEEACH", 
    "ORDERLINENUMBER", 
    "SALES", 
    "DAYS_SINCE_LASTORDER", 
    "MSRP", 
    "ORDERDATE_C", 
    "STATUS_C", "PRODUCTLINE_C", "PRODUCTCODE_C", "CUSTOMERNAME_C", 
    "PHONE_C", "ADDRESSLINE1_C", "CITY_C", "POSTALCODE_C", 
    "COUNTRY_C", "CONTACTLASTNAME_C", "CONTACTFIRSTNAME_C", "DEALSIZE_C"
               ]].corr()

# Membuat plot heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5, annot_kws={"size": 8})

plt.title("Correlation Heatmap - Auto Sales Data", fontsize=14, fontweight="bold")
plt.tight_layout()
plt.show()

## RFM Analysis (Recency, Frequency, Monetary)

In [ ]:
df['ORDERDATE'] = pd.to_datetime(df['ORDERDATE'], format='%d/%m/%Y')

# 3. Tentukan tanggal referensi (1 hari setelah tanggal transaksi paling akhir)
reference_date = df['ORDERDATE'].max() + pd.Timedelta(days=1)

# 4. Agregasi RFM berdasarkan nama pelanggan (CUSTOMERNAME)
rfm = df.groupby('CUSTOMERNAME').agg({
    'ORDERDATE': lambda x: (reference_date - x.max()).days,  # Recency
    'ORDERNUMBER': 'nunique',                                # Frequency
    'SALES': 'sum'                                           # Monetary
}).reset_index()

# Rename kolom agar jelas
rfm.columns = ['CustomerName', 'Recency', 'Frequency', 'Monetary']

# 5. Hitung Skor RFM (skala 1-5 menggunakan qcut/rank)
rfm['R_Score'] = pd.qcut(rfm['Recency'].rank(method='first'), 5, labels=[5, 4, 3, 2, 1]).astype(int)
rfm['F_Score'] = pd.qcut(rfm['Frequency'].rank(method='first'), 5, labels=[1, 2, 3, 4, 5]).astype(int)
rfm['M_Score'] = pd.qcut(rfm['Monetary'].rank(method='first'), 5, labels=[1, 2, 3, 4, 5]).astype(int)

# Gabungkan skor menjadi gabungan string (contoh: '555', '422')
rfm['RFM_Score'] = rfm['R_Score'].astype(str) + rfm['F_Score'].astype(str) + rfm['M_Score'].astype(str)

# 6. Buat aturan segmentasi pelanggan
def assign_segment(row):
    r, f = row['R_Score'], row['F_Score']
    if r >= 4 and f >= 4:
        return 'Champions'
    elif r >= 3 and f >= 3:
        return 'Loyal Customers'
    elif r >= 3 and f <= 2:
        return 'Potential Loyalists'
    elif r <= 2 and f >= 3:
        return 'At Risk'
    else:
        return 'Hibernating Customers'

rfm['Segment'] = rfm.apply(assign_segment, axis=1)
rfm

In [ ]:
# Menampilkan jumlah pelanggan di setiap segmen
print("\nJumlah Pelanggan per Segmen:")
print(rfm['Segment'].value_counts())

In [ ]:
df

## Kesimpulan

Data data_marketing_growth_analytics ini tidak memiliki Missing value, Duplikasi dan tidak ada data yang typo, namu ada data yang Outlier. solusi untuk mengatasai Outlier adalah dengan mempertahankannya.